project: grokking
program: grokking/cli.py
method: grid

metric:
  name: validation_loss
  goal: minimize

parameters:
  operation:
    value: "x/y"
  training_fraction:
    values: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  num_layers:
    value: 2
  dim_model:
    value: 128
  num_heads:
    value: 4
  prime:
    value: 97
  batch_size:
    value: 512
  learning_rate:
    value: 1e-3
  weight_decay:
    value: 1
  num_steps:
    value: 1e5
  device:
    value: cuda
