method: grid
metric:
  goal: minimize
  name: validation_loss
parameters:
  batch_size:
    values:
      - 1
      - 8
      - 32
      - 128
      - 512
      - 1024
  device:
    value: cuda
  dim_model:
    value: 128
  learning_rate:
    value: 0.001
  noise_level:
    values:
      - 0
      - 0.1
      - 1
  num_heads:
    value: 4
  num_layers:
    value: 2
  num_steps:
    value: 100000
  operation:
    value: x/y
  prime:
    values:
      - 47
      - 97
      - 197
      - 293
      - 563
      - 997
  scale_factor:
    values:
      - 0.1
      - 1
      - 10
  training_fraction:
    value: 0.3
  weight_decay:
    values:
      - 0.1
      - 1
program: grokking/cli.py
project: grokking
